In [1]:
import numpy as np

In [2]:
x=  np.random.randint(2,20,10)

In [3]:
x

array([11,  6,  6, 18, 14,  4,  9, 19,  7, 16], dtype=int32)

In [4]:
x.mean()

np.float64(11.0)

In [8]:
x[1]=700

In [9]:
x

array([ 11, 700,   6,  18,  14,   4,   9,  19,   7,  16], dtype=int32)

In [10]:
x.mean()

np.float64(80.4)

In [11]:
x1=  np.random.randint(2,20,10)

In [12]:
x1

array([ 7, 17, 17,  2,  8, 15, 18,  7,  2,  9], dtype=int32)

In [13]:
x1.sort()

In [14]:
x1

array([ 2,  2,  7,  7,  8,  9, 15, 17, 17, 18], dtype=int32)

In [15]:
x1.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [16]:
np.median(x1)

np.float64(8.5)

In [17]:
x2=  np.random.randint(2,20,10)

In [18]:
x2

array([17,  7,  9, 19,  4, 16,  5,  3,  3, 19], dtype=int32)

In [19]:
np.median(x2)

np.float64(8.0)

In [20]:
x2.sort()

In [21]:
x2

array([ 3,  3,  4,  5,  7,  9, 16, 17, 19, 19], dtype=int32)