In [1]:
import numpy as np

In [2]:
x=np.array([2,7,1,5])

In [3]:
x

array([2, 7, 1, 5])

In [4]:
x.mean()

np.float64(3.75)

In [9]:
x=np.array([5,7,12,20])
f=np.array([2,1,3,4])
fx=f*x

In [10]:
f

array([2, 1, 3, 4])

In [11]:
x

array([ 5,  7, 12, 20])

In [12]:
fx

array([10,  7, 36, 80])

In [13]:
fx.sum()

np.int64(133)

In [14]:
f.sum()

np.int64(10)

In [15]:
fx.sum()/f.sum()

np.float64(13.3)