In [1]:
import numpy as np

In [3]:
B=np.diag([2,7,1])

In [4]:
B

array([[2, 0, 0],
       [0, 7, 0],
       [0, 0, 1]])

In [5]:
E=np.diag([1,0,7,4])

In [6]:
E

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 4]])

In [7]:
np.identity(3)*7

array([[7., 0., 0.],
       [0., 7., 0.],
       [0., 0., 7.]])

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
-2*np.identity(2)

array([[-2., -0.],
       [-0., -2.]])

In [10]:
B

array([[2, 0, 0],
       [0, 7, 0],
       [0, 0, 1]])

In [11]:
B.ndim

2

In [12]:
B.dtype

dtype('int64')

In [13]:
B.shape

(3, 3)

In [14]:
B.size

9

In [15]:
B

array([[2, 0, 0],
       [0, 7, 0],
       [0, 0, 1]])

In [16]:
B.T

array([[2, 0, 0],
       [0, 7, 0],
       [0, 0, 1]])

In [20]:
D=np.random.randint(2,7,(2,4))

In [21]:
D

array([[3, 5, 2, 6],
       [4, 2, 5, 5]])

In [22]:
D.T

array([[3, 4],
       [5, 2],
       [2, 5],
       [6, 5]])