In [1]:
A={4,7,3,2,4,15}


In [2]:
A

{2, 3, 4, 7, 15}

In [3]:
len(A)

5

In [4]:
A= {1,7,9,4}
B={2,15,3,4,7}

In [5]:
A.intersection(B)

{4, 7}

In [6]:
B.intersection(A)

{4, 7}

In [7]:
C= {3,20,15}

In [8]:
A.intersection(C)

set()

In [9]:
A.union(B)

{1, 2, 3, 4, 7, 9, 15}

In [10]:
A.union(B).union(C) # method chaining

{1, 2, 3, 4, 7, 9, 15, 20}

In [11]:
A.difference(B)

{1, 9}

In [12]:
B.difference(A)

{2, 3, 15}

In [ ]:
## Symmetric difference 

In [13]:
A.union(B)

{1, 2, 3, 4, 7, 9, 15}

In [14]:
A.intersection(B)

{4, 7}

In [15]:
#A symm B={1,2,3,9,15}

In [16]:
A.symmetric_difference(B)

{1, 2, 3, 9, 15}

# Numpy

In [17]:
## illustration

In [19]:
a=[3,5,6,2,1]
b=[5,6,8,4,-3]
# c=[8,11,14,6,-2]

In [20]:
c=[]
for item in zip(a,b):
    c.append(item[0]+item[1])
print(c)

[8, 11, 14, 6, -2]


In [21]:
v=[6,7]

In [22]:
x1=v[0]
x2=v[1]
print(x1)
print(x2)

6
7


In [ ]:
## unpacking

In [23]:
v

[6, 7]

In [24]:
x3, x4= v

In [25]:
x3

6

In [26]:
x4

7

In [29]:
z=[4,6,4]
x1,x2,x3=z
print(x1)
print(x2)
print(x3)

4
6
4


In [30]:
z=[4,6,4]
x1,x2,_=z
print(x1)
print(x2)

4
6


In [33]:
x5,*x6=z

In [34]:
x5

4

In [35]:
x6

[6, 4]

In [36]:
c=[]
for x,y in zip(a,b):
    c.append(x+y)
print(c)

[8, 11, 14, 6, -2]


In [37]:
c=[]
for x,y in zip(a,b):
    c.append(x*y)
print(c)

[15, 30, 48, 8, -3]


In [38]:
c=[]
for x,y in zip(a,b):
    c.append(x/y)
print(c)

[0.6, 0.8333333333333334, 0.75, 0.5, -0.3333333333333333]


In [39]:
a+b # wrong

[3, 5, 6, 2, 1, 5, 6, 8, 4, -3]

In [40]:
import numpy as np

In [42]:
a=np.array([3,5,6,2,1])
b=np.array([5,6,8,4,-3])
a+b

array([ 8, 11, 14,  6, -2])

In [43]:
a*b

array([15, 30, 48,  8, -3])

In [44]:
a/b

array([ 0.6       ,  0.83333333,  0.75      ,  0.5       , -0.33333333])

In [45]:
a

array([3, 5, 6, 2, 1])

In [46]:
b

array([ 5,  6,  8,  4, -3])

In [47]:
a**2

array([ 9, 25, 36,  4,  1])

In [49]:
x6

[6, 4]

In [54]:
c*2

[0.6,
 0.8333333333333334,
 0.75,
 0.5,
 -0.3333333333333333,
 0.6,
 0.8333333333333334,
 0.75,
 0.5,
 -0.3333333333333333]

In [55]:
c+c

[0.6,
 0.8333333333333334,
 0.75,
 0.5,
 -0.3333333333333333,
 0.6,
 0.8333333333333334,
 0.75,
 0.5,
 -0.3333333333333333]

In [56]:
a

array([3, 5, 6, 2, 1])

In [57]:
2*a

array([ 6, 10, 12,  4,  2])