In [1]:
import numpy as np

In [2]:
A= np.random.randint(2,10,(3,3))

In [3]:
A

array([[6, 7, 9],
       [4, 7, 6],
       [3, 3, 3]])

In [4]:
A.trace()

16

In [5]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
range(1,7,0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [9]:
np.arange(1,7,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [10]:
a=np.arange(4)

In [11]:
a

array([0, 1, 2, 3])

In [12]:
b=np.arange(1,6)

In [13]:
b

array([1, 2, 3, 4, 5])

In [14]:
a+b

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [15]:
c=np.random.randint(2,9,4)

In [16]:
c

array([7, 6, 3, 4])

In [17]:
a

array([0, 1, 2, 3])

In [18]:
a+c

array([7, 7, 5, 7])

In [19]:
c-a

array([7, 5, 1, 1])

In [20]:
a.ndim

1

In [21]:
A=np.random.randint(3,8,(2,3))
B=np.random.randint(3,12,(2,3))

In [22]:
A

array([[5, 5, 3],
       [4, 6, 7]])

In [23]:
B

array([[11,  8, 10],
       [10,  6,  3]])

In [24]:
A+B

array([[16, 13, 13],
       [14, 12, 10]])

In [25]:
A/B

array([[0.45454545, 0.625     , 0.3       ],
       [0.4       , 1.        , 2.33333333]])

In [26]:
a

array([0, 1, 2, 3])

In [27]:
a+3

array([3, 4, 5, 6])

In [28]:
2*a

array([0, 2, 4, 6])

In [29]:
d=np.array([4])

In [30]:
d

array([4])

In [31]:
a+d

array([4, 5, 6, 7])

In [32]:
A

array([[5, 5, 3],
       [4, 6, 7]])

In [33]:
v1=np.array([3,4])
v2=np.array([3,4,-1])

In [35]:
A

array([[5, 5, 3],
       [4, 6, 7]])

In [36]:
A+v1

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [37]:
A+v2

array([[ 8,  9,  2],
       [ 7, 10,  6]])

In [38]:
a

array([0, 1, 2, 3])

In [39]:
c

array([7, 6, 3, 4])

In [40]:
a*c

array([ 0,  6,  6, 12])

In [41]:
A=np.array([[2,3],[1,4]])
B=np.array([[2,1,7],[1,2,-2]])

In [42]:
A

array([[2, 3],
       [1, 4]])

In [43]:
B

array([[ 2,  1,  7],
       [ 1,  2, -2]])

In [45]:
A*B

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [46]:
A@B

array([[ 7,  8,  8],
       [ 6,  9, -1]])

In [47]:
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)