In [1]:
scores =[70,20,60,40]
target_scores=[]
for score in scores:
    if score>=50:
        target_scores.append(score)
print(target_scores)

[70, 60]


In [2]:
import numpy  as  np

In [3]:
scores =np.array(scores)

In [4]:
scores

array([70, 20, 60, 40])

In [6]:
t=scores>=50

In [7]:
t

array([ True, False,  True, False])

In [8]:
scores

array([70, 20, 60, 40])

In [12]:
t

array([ True, False,  True, False])

In [9]:
scores[t]

array([70, 60])

In [10]:
scores

array([70, 20, 60, 40])

In [11]:
scores[np.array([True,False,True,True])] # Masking

array([70, 60, 40])

In [13]:
scores.mean()

np.float64(47.5)

In [14]:
scores<scores.mean()

array([False,  True, False,  True])

In [15]:
c=scores<scores.mean()

In [16]:
c

array([False,  True, False,  True])

In [17]:
scores

array([70, 20, 60, 40])

In [18]:
scores[c]

array([20, 40])

In [19]:
scores.max()-scores.min()

np.int64(50)

In [20]:
scores<scores.max()-scores.min()

array([False,  True, False,  True])

In [21]:
scores

array([70, 20, 60, 40])

In [ ]:
scores[scores<scores.max()-scores.min()]

In [22]:
x=np.random.randint(2,50,(4,2))

In [23]:
x

array([[ 2, 38],
       [47, 36],
       [49, 33],
       [33, 27]], dtype=int32)

In [24]:
x.mean()

np.float64(33.125)

In [25]:
x>x.mean()

array([[False,  True],
       [ True,  True],
       [ True, False],
       [False, False]])

In [26]:
x

array([[ 2, 38],
       [47, 36],
       [49, 33],
       [33, 27]], dtype=int32)

In [27]:
x[x>x.mean()]

array([38, 47, 36, 49], dtype=int32)

In [28]:
scores

array([70, 20, 60, 40])

In [30]:
scores>50 and scores<70

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [32]:
scores>50 & scores<70

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [33]:
(scores>50) & (scores<70)

array([False, False,  True, False])

In [34]:
scores[(scores>50) & (scores<70)]

array([60])

In [35]:
scores[(scores>50) | (scores<70)]

array([70, 20, 60, 40])

In [36]:
scores>60

array([ True, False, False, False])

In [37]:
~(scores>60)

array([False,  True,  True,  True])

In [38]:
scores[~(scores>60)]

array([20, 60, 40])

In [39]:
## Indexing and slicing

In [40]:
scores

array([70, 20, 60, 40])

In [41]:
scores[0]

np.int64(70)

In [42]:
scores[1]

np.int64(20)

In [43]:
scores

array([70, 20, 60, 40])

In [44]:
scores[0:3:2]

array([70, 60])

In [ ]:
## fancy indexing

In [46]:
scores[0,1,3]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [47]:
scores[[0,1,3]]

array([70, 20, 40])

In [48]:
v= np.random.randint(0,100,12)

In [49]:
v

array([43, 61, 37, 80, 51, 59, 35, 42,  6, 39, 62, 43], dtype=int32)

In [50]:
scores(0,1,3)

TypeError: 'numpy.ndarray' object is not callable

In [51]:
x

array([[ 2, 38],
       [47, 36],
       [49, 33],
       [33, 27]], dtype=int32)

In [52]:
x[0][0]

np.int32(2)

In [53]:
x[0]

array([ 2, 38], dtype=int32)

In [54]:
x[0][0]

np.int32(2)

In [55]:
x[2][1]

np.int32(33)

In [56]:
x[0,0]

np.int32(2)

In [57]:
x[2,1]

np.int32(33)

In [60]:
x[:,0]

array([ 2, 47, 49, 33], dtype=int32)

In [59]:
x

array([[ 2, 38],
       [47, 36],
       [49, 33],
       [33, 27]], dtype=int32)

In [61]:
x[:,-1]

array([38, 36, 33, 27], dtype=int32)

In [63]:
x[0:2,:]

array([[ 2, 38],
       [47, 36]], dtype=int32)

In [62]:
scores

array([70, 20, 60, 40])

In [66]:
scores[0:2]

array([70, 20])

In [65]:
x[1:4:2,1]

array([36, 27], dtype=int32)

In [64]:
x

array([[ 2, 38],
       [47, 36],
       [49, 33],
       [33, 27]], dtype=int32)

In [67]:
# reshaping

In [68]:
x

array([[ 2, 38],
       [47, 36],
       [49, 33],
       [33, 27]], dtype=int32)

In [69]:
x.shape

(4, 2)

In [70]:
x.size

8

In [71]:
x

array([[ 2, 38],
       [47, 36],
       [49, 33],
       [33, 27]], dtype=int32)

In [72]:
x.reshape(2,4)

array([[ 2, 38, 47, 36],
       [49, 33, 33, 27]], dtype=int32)

In [73]:
x.reshape(1,8)

array([[ 2, 38, 47, 36, 49, 33, 33, 27]], dtype=int32)

In [75]:
x.reshape(8,1)

array([[ 2],
       [38],
       [47],
       [36],
       [49],
       [33],
       [33],
       [27]], dtype=int32)

In [76]:
x.reshape(2,3)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [77]:
x.reshape(2,-1)

array([[ 2, 38, 47, 36],
       [49, 33, 33, 27]], dtype=int32)

In [78]:
x.reshape(-1,1)

array([[ 2],
       [38],
       [47],
       [36],
       [49],
       [33],
       [33],
       [27]], dtype=int32)

In [79]:
x.reshape(3,-1)

ValueError: cannot reshape array of size 8 into shape (3,newaxis)